---
version: '3'
services:
  runserver:
    user: bew
    image: ltj-project-django-virtualenv
    build: .
    command: /home/bew/.venv/bin/python3 manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - .:/home/bew/bew
      # - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
    links:
      - postgis
    environment:
# Project specific env vars for this project:
# Service level env vars:
      - HTTPS=off
      - LANG=en_US.utf8
      - LC_ALL=en_US.UTF-8
      - LC_LANG=en_US.UTF-8
      - DJANGO_SETTINGS_MODULE=local_settings
# Infra env vars:
      - PYTHONUNBUFFERED=1
      - SSH_AUTH_SOCK
      - GIT_AUTHOR_EMAIL
      - GIT_AUTHOR_NAME
      - GIT_COMMITTER_EMAIL
      - GIT_COMMITTER_NAME
    networks:
      - network
    depends_on:
      - postgis
    stdin_open: true
    tty: true

  postgis:
    image: postgis/postgis:13-3.3-alpine
    environment:
      - POSTGRES_PASSWORD=luontotieto
      - POSTGRES_USER=ltj
      - POSTGRES_DB=ltj
      - LANG=fi_FI.UTF-8
    volumes:
      - ./postgis-initdb:/docker-entrypoint-initdb.d
      - postgis:/var/lib/postgis/data
    ports:
      - 5432
    networks:
      - network

volumes:
  postgis:

networks:
  network:
