---
version: '3'
services:
  runserver:
    user: bew
    image: ltj_bergenia-project-django-virtualenv
    build: .
    command: /home/bew/.venv/bin/python3 manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - .:/home/bew/bew
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
    links:
      - postgis
      - memcached
      - redis
      - rabbitmq
    environment:
# Project specific env vars for this project:
      - DEBUG=True
      - SECRET_KEY="foo"
      - SHARED_SECRET="secret"
      - DATABASE_URL="postgis://bergenia:bergenia@postgis:5432/bergenia"
# Service level env vars:
      - HTTPS=off
      - LANG=en_US.utf8
      - LC_ALL=en_US.UTF-8
      - LC_LANG=en_US.UTF-8
      - DJANGO_SETTINGS_MODULE=local_settings
# Infra env vars:
      - PYTHONUNBUFFERED=1
      - SSH_AUTH_SOCK
      - GIT_AUTHOR_EMAIL
      - GIT_AUTHOR_NAME
      - GIT_COMMITTER_EMAIL
      - GIT_COMMITTER_NAME
    networks:
      - network
    depends_on:
      - postgis
      - memcached
      - redis
    stdin_open: true
    tty: true

  postgis:
    image: postgis/postgis:10-3.2-alpine
    environment:
      - POSTGRES_PASSWORD=bergenia
      - POSTGRES_USER=bergenia
      - POSTGRES_DB=bergenia
    volumes:
      - postgis:/var/lib/postgis/data
    ports:
      - 5432
    networks:
      - network

  memcached:
    image: memcached:1.5.6
    networks:
      - network

  redis:
    image: redis:4.0.9
    networks:
      - network

  rabbitmq:
    image: rabbitmq:3.6.10
    environment:
      - RABBITMQ_DEFAULT_VHOST=bergenia
    networks:
      - network
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgis:

networks:
  network:
